--- #YAML:1.0
name:               Date-Holidays-UK-EnglandAndWales
version:            0.03
abstract:           Public Holidays in England and Wales
author:
    - Lee Goddard <lgoddard-at-cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
    Tie::Hash:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
